### ISSUE TITLE
Correcciones ejercicio html

### ISSUE THREAD

**Issue by Xaviju** [antoniozapata/Curso-Coding#1]
Hola Antonio, te dejo acá algunas correcciones sobre el ejercicio https://github.com/antoniozapata/Curso-Coding/blob/7f7a50727848c17bfeaff3593e519c90a79b484c/HTML/Deberes%20clase%201/index.html

1. La etiqueta `<style>`, que aún no hemos aprendido, siempre debe ir en minúsculas. En esta parte de CSS tienes algunas malas prácticas que iremos viendo a partir de la semana que viene
https://github.com/antoniozapata/Curso-Coding/blob/7f7a50727848c17bfeaff3593e519c90a79b484c/HTML/Deberes%20clase%201/index.html#L6

2. El atributo `<width>` de esta línea es un atributo válido en HTML pero desaconsejado. Para estilos usaremos CSS
https://github.com/antoniozapata/Curso-Coding/blob/7f7a50727848c17bfeaff3593e519c90a79b484c/HTML/Deberes%20clase%201/index.html#L29

3. La etiqueta `<fieldset>` es una etiqueta que solo se usa en formularios, lo veremos la semana que viene. En este caso es incorrecta y parece que lo que debería haber aquí es un `<section>`
https://github.com/antoniozapata/Curso-Coding/blob/7f7a50727848c17bfeaff3593e519c90a79b484c/HTML/Deberes%20clase%201/index.html#L32

4. La etiqueta `legend` es una etiqueta que solo se usa en formularios, lo veremos la semana que viene. En este caso es incorrecta y parece que lo que debería haber aquí según el orden de jerarquía de tu página es un `<h3>`
https://github.com/antoniozapata/Curso-Coding/blob/7f7a50727848c17bfeaff3593e519c90a79b484c/HTML/Deberes%20clase%201/index.html#L33

5. No has puesto ningún `<ol>` ni ningún `<strong>`. 

6. La etiqueta `<u>` no existe :smile: Tienes varias, revísalo. Debería ser un `<li>` que debe contenter todo el texto.
https://github.com/antoniozapata/Curso-Coding/blob/7f7a50727848c17bfeaff3593e519c90a79b484c/HTML/Deberes%20clase%201/index.html#L71

7. Esta etiqueta `<img>` no tiene atributo `alt`
https://github.com/antoniozapata/Curso-Coding/blob/7f7a50727848c17bfeaff3593e519c90a79b484c/HTML/Deberes%20clase%201/index.html#L113

Tu HTML no ha sido validado por el validador del W3C https://validator.w3.org/
Genial el uso del resto de tags

**Comment by Xaviju** [comment]
![Gif hi five](https://media.giphy.com/media/l3q2yZIjG0RxM1sis/giphy.gif)

**Comment by Xaviju** [comment]
Cuando corrijas este ejercicio, recuerda dale a `Close issue`.
Ánimo, está muy bien y 1000 puntos por investigar tags por internet. Una vez aprendamos a diferenciar la información es una habilidad muy importante.
¡Enhorabuena!

**Comment by antoniozapata** [comment]
> Hola Antonio, te dejo acá algunas correcciones sobre el ejercicio https://github.com/antoniozapata/Curso-Coding/blob/7f7a50727848c17bfeaff3593e519c90a79b484c/HTML/Deberes%20clase%201/index.html
> 
> 1. La etiqueta `<style>`, que aún no hemos aprendido, siempre debe ir en minúsculas. En esta parte de CSS tienes algunas malas prácticas que iremos viendo a partir de la semana que viene
>    
>      
>        
>          [Curso-Coding/HTML/Deberes clase 1/index.html](https://github.com/antoniozapata/Curso-Coding/blob/7f7a50727848c17bfeaff3593e519c90a79b484c/HTML/Deberes%20clase%201/index.html#L6)
>        
>        
>             Line 6
>          in
>          [7f7a507](/antoniozapata/Curso-Coding/commit/7f7a50727848c17bfeaff3593e519c90a79b484c)
>        
>        
>        
>        
>    
>            
>              
>               <Style>
> 2. El atributo `<width>` de esta línea es un atributo válido en HTML pero desaconsejado. Para estilos usaremos CSS
>    
>      
>        
>          [Curso-Coding/HTML/Deberes clase 1/index.html](https://github.com/antoniozapata/Curso-Coding/blob/7f7a50727848c17bfeaff3593e519c90a79b484c/HTML/Deberes%20clase%201/index.html#L29)
>        
>        
>             Line 29
>          in
>          [7f7a507](/antoniozapata/Curso-Coding/commit/7f7a50727848c17bfeaff3593e519c90a79b484c)
>        
>        
>        
>        
>    
>            
>              
>               <img src="Antonio.jpg" alt="mi foto de perfil" width="100" id="foto">
> 3. La etiqueta `<fieldset>` es una etiqueta que solo se usa en formularios, lo veremos la semana que viene. En este caso es incorrecta y parece que lo que debería haber aquí es un `<section>`
>    
>      
>        
>          [Curso-Coding/HTML/Deberes clase 1/index.html](https://github.com/antoniozapata/Curso-Coding/blob/7f7a50727848c17bfeaff3593e519c90a79b484c/HTML/Deberes%20clase%201/index.html#L32)
>        
>        
>             Line 32
>          in
>          [7f7a507](/antoniozapata/Curso-Coding/commit/7f7a50727848c17bfeaff3593e519c90a79b484c)
>        
>        
>        
>        
>    
>            
>              
>               <fieldset>
> 4. La etiqueta `legend` es una etiqueta que solo se usa en formularios, lo veremos la semana que viene. En este caso es incorrecta y parece que lo que debería haber aquí según el orden de jerarquía de tu página es un `<h3>`
>    
>      
>        
>          [Curso-Coding/HTML/Deberes clase 1/index.html](https://github.com/antoniozapata/Curso-Coding/blob/7f7a50727848c17bfeaff3593e519c90a79b484c/HTML/Deberes%20clase%201/index.html#L33)
>        
>        
>             Line 33
>          in
>          [7f7a507](/antoniozapata/Curso-Coding/commit/7f7a50727848c17bfeaff3593e519c90a79b484c)
>        
>        
>        
>        
>    
>            
>              
>               <legend>Datos Generales</legend>
> 5. No has puesto ningún `<ol>` ni ningún `<strong>`.
> 6. La etiqueta `<u>` no existe 😄 Tienes varias, revísalo. Debería ser un `<li>` que debe contenter todo el texto.
>    
>      
>        
>          [Curso-Coding/HTML/Deberes clase 1/index.html](https://github.com/antoniozapata/Curso-Coding/blob/7f7a50727848c17bfeaff3593e519c90a79b484c/HTML/Deberes%20clase%201/index.html#L71)
>        
>        
>             Line 71
>          in
>          [7f7a507](/antoniozapata/Curso-Coding/commit/7f7a50727848c17bfeaff3593e519c90a79b484c)
>        
>        
>        
>        
>    
>            
>              
>               <u>Funciones:</u> Adiestramiento y cursos sobre la operación de los Sistemas Administrativos, contables, tributarios y de RRHH de Gálac Software.
> 7. Esta etiqueta `<img>` no tiene atributo `alt`
>    
>      
>        
>          [Curso-Coding/HTML/Deberes clase 1/index.html](https://github.com/antoniozapata/Curso-Coding/blob/7f7a50727848c17bfeaff3593e519c90a79b484c/HTML/Deberes%20clase%201/index.html#L113)
>        
>        
>             Line 113
>          in
>          [7f7a507](/antoniozapata/Curso-Coding/commit/7f7a50727848c17bfeaff3593e519c90a79b484c)
>        
>        
>        
>        
>    
>            
>              
>               <img src="https://gratisography.com/thumbnails/gratisography-artist-paint-brushes-thumbnail-small.jpg">
> 
> Tu HTML no ha sido validado por el validador del W3C https://validator.w3.org/
> Genial el uso del resto de tags

**Muy bien, creo haber hecho las correcciones necesarias al ejercicio, actualice el [repositorio](https://github.com/antoniozapata/Curso-Coding/tree/master/HTML/Deberes%20clase%201) con las correcciones, si puedes échale un ojo por favor.**

**Comment by antoniozapata** [comment]
También pude usar el enlace del validador.

**Document checking completed. No errors or warnings to show.**

**Comment by Xaviju** [comment]
¡Lo reviso de nuevo!

**Comment by Xaviju** [comment]
Veo que el ejercicio está correcto y no veo fallos importantes (¡enhorabuena!) 
Lo que te paso a continuación son consejos de mejora ya que has corregido el ejercicio:

Tu `header` es algo pobre (solo tiene el título) quizá toda la información que tienes  debajo (nombre, dirección, etc.) tendría sentido en el `header`

Tu `h1` es poco descriptivo. Piensa que ese es el título que va a definir tu página. Es mejor darle información que diferencie para usuarios o robots que visiten tu web. Por ejemplo: "curriculum de Antonio Zapata" o algo así. Podrías incluso borrar el `h2` de la linea 28

En esta lista, yo hubiese usado un `ol` en lugar de un `ul` porque se trata de una lista donde el orden es importante ya que lo ordenaste por fecha 
https://github.com/antoniozapata/Curso-Coding/blob/d1da94f53e684ab93268be5c02552a3ddc460393/HTML/Deberes%20clase%201/index.html#L49

Lo mismo acá 
https://github.com/antoniozapata/Curso-Coding/blob/d1da94f53e684ab93268be5c02552a3ddc460393/HTML/Deberes%20clase%201/index.html#L65

En cambio aquí sí usaste un `ol` pero el orden no parece imporante.
https://github.com/antoniozapata/Curso-Coding/blob/d1da94f53e684ab93268be5c02552a3ddc460393/HTML/Deberes%20clase%201/index.html#L84

Si finalmente conviertes el `h2` en un `h1` es posible que para esta página bastaría con tener solo `h1` y `h2`.

Espero que te sirva la correción ¡Buen trabajo!

**Comment by antoniozapata** [comment]
Muy bien, ya he hecho las correcciones, precisamente discutía con victoria el hecho de que no listaría de forma numérica debido a que están ya las fechas, pero entiende el criterio que me das. En realidad la numeración la hice para integrarla al ejercicio.

**Comment by Xaviju** [comment]
Posteriormente, con CSS podemos quitar los números, ahora no es importante. :muscle:

**Comment by antoniozapata** [comment]
¿Pudiera incluir en el head la info repetida?
