### ISSUE TITLE
Correción tarea 16 de abril

### ISSUE THREAD

**Issue by riboher** [antoniozapata/Curso-Coding#2]
Hola Antonio!

Muy buen trabajo en general, te hago algunos comentarios para que puedas mejorarlo pero en cualquier caso, enhorabuena por la tarea!

En el fichero `styles.css`:
1. En lugar de utilizar la propiedad `text-align`, si lo que querías era centrar todo el contenido de tu página, es mejor que utilices la propiedad `margin` con los valores `0 auto`. De esta forma, no solo el contenido de tus elementos block se centrarán, sino que todo contenedor dentro de tu documento lo hará también.

2. Intenta no repetir tanto código. Date cuenta que hay muchos elementos de tu página que comparten estilos. CSS te permite agruparlos separando los selectores con comas, de esta forma, tus elementos `.formulario` y `.quienessomos` podrían quedarse así:

```
.formulario,
.quienessomos {
    background-color: #E6F9F2;
    padding: 0 20px 20px 20px;
    font-size: 16px;
}
```
Hay otro par de clases con el que podrías ahorrarte unas líneas de esta manera, te dejo que lo busques y lo cambies tú mismo :).

3. Me ha gustado mucho que uses hexadecimal para los colores, habrás comprobado que hay muchas más posibilidades que usando los colores por defecto que te proporciona el navegador. Intenta usarlos en todos los casos, incluido cuando utilizas white `#fff` o black `#000`.

4. Aunque no está mal, como os dije, es recomendabe que os acostumbreis a usar solo clases en vuestros ficheros css. Os permite abstraer mucho más vuestro código y no depender tanto de la estructura HTML en sí. Intenta cambiar las etiquetas `html`, `header`y `footer` por clases CSS.

En el fichero HTML:

1. El select de tipo_de_pago puedes hacerlo con otro tipo de input que tiene más sentido, el radio button. Intenta rehacer si quieres este trozo con ese tipo de input. 

2. Recuerda que usar estilos en línea es muy mala práctica. Elimina el estilo que has aplicado a la img de la línea 102, dale una clase e inclúyelo en tu fichero CSS
https://github.com/antoniozapata/Curso-Coding/blob/ca400dbc189b7d44b90e2b47d92251af80c2bc84/Deberes/Deberes_css1/templates/index.html#L102

Por lo demás lo veo bastante bien, muy buen trabajo!

**Comment by antoniozapata** [comment]
Corrigiendo, gracias.
