### ISSUE TITLE
Correcciones deberes_webdesigner

### ISSUE THREAD

**Issue by Xaviju** [antoniozapata/Curso-Coding#3]
Hola Antonio, te dejo algunas correcciones:

El HTML no valida en el W3C, tienes algún `<div>` mal cerrado y eso puede causar problemas en algunos navegadores o en javascript.

Estos enlaces están bien estructurados, pero siempre que un enlace contenga una imagen, esa imagen tiene que tener un `alt` relleno. Entiendo que si la imagen es clicable, ya no se trata de una imagen con finalidad puramente estética, sino que tiene funcionalidad.
https://github.com/antoniozapata/Curso-Coding/blob/49d879dd2d72319008b0b6ebe73eb46eb5f69002/Deberes/deberes_webdesigner/templates/index.html#L29

En este punto la indentación es incorrecta
https://github.com/antoniozapata/Curso-Coding/blob/49d879dd2d72319008b0b6ebe73eb46eb5f69002/Deberes/deberes_webdesigner/templates/index.html#L23

Son detalles menores excepto de la validación ¡Por alguna razón se os olvida a todos!
Enhorabuena por el trabajo, este HTML tiene un nivel muy alto :)
¿Cómo va el CSS?

**Comment by antoniozapata** [comment]
Listo, hoy hago el CSS y te lo hago llegar, gracias por las observaciones.

**"Document checking completed. No errors or warnings to show."**
