### ISSUE TITLE
Corrección tarea 7 de mayo

### ISSUE THREAD

**Issue by riboher** [antoniozapata/Curso-Coding#4]
Hola Antonio!

Te dejo aquí algunas correciones sobre el ejercicio. En general está todo genial, se nota que has puesto esfuerzo en que tu código esté limpio y legible. De hecho, así a priori, no veo fallos grandes en el código, es código que funciona y es fácil de leer, por lo que te voy a decir simplemente algunas cosas de estilo y algún fallo tonto que he estado viendo. Enhorabuena de antemano en cualquier caso!

**HTML**
https://github.com/antoniozapata/Curso-Coding/blob/73ce4499e597e6e8573d724420ac0afdafc87b45/Deberes/deberes_webdesigner/templates/index.html#L101
- Acostúmbrate a no dejar vacíos los atributos `alt`de tus imágenes. Mejora la accesibilidad de tu página y necesitarás mostrar algo en casode que la imagen no se cargue correctamente.

https://github.com/antoniozapata/Curso-Coding/blob/73ce4499e597e6e8573d724420ac0afdafc87b45/Deberes/deberes_webdesigner/templates/index.html#L20
https://github.com/antoniozapata/Curso-Coding/blob/73ce4499e597e6e8573d724420ac0afdafc87b45/Deberes/deberes_webdesigner/templates/index.html#L29
https://github.com/antoniozapata/Curso-Coding/blob/73ce4499e597e6e8573d724420ac0afdafc87b45/Deberes/deberes_webdesigner/templates/index.html#L49
- Intenta ser consistente a la hora de nombrar tus clases. Intenta no variar entre no dejar espacios entre palabras, utilizar guiones `-` o underscore `_`. Como opinión, yo prefiero utilizar siempre el guión para separar las palabras (kebab case)

https://github.com/antoniozapata/Curso-Coding/blob/73ce4499e597e6e8573d724420ac0afdafc87b45/Deberes/deberes_webdesigner/templates/index.html#L138
- La indentación de los elementos `li` de esta lista no es correcta. Están al mismo nivel y deberías indentarlos para que se note que son hijos de `ul`

- Aunque no es incorrecto, veo que has incluido navegación tanto arriba como abajo de la página. Por eso creo que igual que has incluido una etiqueta `<header>`, sería más correcto semánticamente que incluyeses un elemento `<footer>` en la parte inferior.

**CSS**

https://github.com/antoniozapata/Curso-Coding/blob/73ce4499e597e6e8573d724420ac0afdafc87b45/Deberes/deberes_webdesigner/styles/style.css#L7
- Esto no tiene demasiado sentido. No está mal, pero si no vas a mostrar la etiqueta `<h1>`, no es necesario que la incluyas en tu fichero `.html`.

https://github.com/antoniozapata/Curso-Coding/blob/73ce4499e597e6e8573d724420ac0afdafc87b45/Deberes/deberes_webdesigner/styles/style.css#L121
- De nuevo, aunque no es incorrecto, si solo vas a darle valor a una posición del margin, puedes directamente hacer `margin-top: 100px`

https://github.com/antoniozapata/Curso-Coding/blob/73ce4499e597e6e8573d724420ac0afdafc87b45/Deberes/deberes_webdesigner/styles/style.css#L94
- Por el contrario, en esta línea y las posteriores, utilizas 4 reglas distintas para dar un valor de 0, cuando podrías hacer simplemente `padding: 0`.

https://github.com/antoniozapata/Curso-Coding/blob/73ce4499e597e6e8573d724420ac0afdafc87b45/Deberes/deberes_webdesigner/styles/style.css#L101
- Acostúmbrate a usar clases siempre, en general lo has hecho bien en todo el ejercicio pero en ocasiones utilizas directamente el tag html. Mejor dale una clase a ese elemento y utilizála en su lugar.

https://github.com/antoniozapata/Curso-Coding/blob/73ce4499e597e6e8573d724420ac0afdafc87b45/Deberes/deberes_webdesigner/styles/style.css#L150
- Aunque no está mal, probablemente podrías obtener el mismo resultado usando `display: flex` en el elemento padre. Veo que has usado flex en más partes del ejercicio. Intenta hacer lo mismo aquí.

Por lo demás lo que te he dicho más arriba, un buen ejercicio donde se nota que has estado investigando por tu cuenta, enhorabuena!

**Comment by antoniozapata** [comment]
Muchas gracias por las observaciones, tomadas en cuenta y modificadas.
